# Generated by Django 3.2.12 on 2023-12-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
                ('category', models.CharField(blank=True, default=None, max_length=50)),
                ('date_release', models.DateTimeField(auto_now_add=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10)),
            ],
        ),
    ]
